Controllers/BillsController.cs
using ClosedXML.Excel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Authorization;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using Microsoft.Graph;
using Microsoft.Identity.Web;
using Service_Billing.Data;
using Service_Billing.Models;
using Service_Billing.Models.Repositories;
using Service_Billing.ViewModels;
using System.Collections.Immutable;
using System.Data;
using System.Reflection;

namespace Service_Billing.Controllers
{
    public class BillsController : Controller
    {
        private readonly IBillRepository _billRepository;
        private readonly IServiceCategoryRepository _categoryRepository;
        private readonly IClientAccountRepository _clientAccountRepository;
        private readonly IMinistryRepository _ministryRepository;
        private readonly GraphServiceClient _graphServiceClient;
        private readonly MicrosoftIdentityConsentAndConditionalAccessHandler _consentHandler;
        private readonly ILogger<BillsController> _logger;
        private readonly IAuthorizationService _authorizationService;
        private readonly IBusinessAreaRepository _businessAreaRepository;
        private readonly ServiceBillingContext _serviceBillingContext;
        private readonly IFiscalPeriodRepository _fiscalPeriodRepository;
        private readonly IFiscalHistoryRepository _fiscalHistoryRepository;
        private readonly IChangeLogRepository _changeLogRepository;

        public BillsController(ILogger<BillsController> logger,
            IBillRepository billRepository,
            IServiceCategoryRepository categoryRepository,
            IClientAccountRepository clientAccountRepository,
            IMinistryRepository ministryRepository,
            IAuthorizationService authorizationService,
            IBusinessAreaRepository businessAreaRepository,
            IFiscalPeriodRepository fiscalPeriodRepository,
            IFiscalHistoryRepository fiscalHistoryRepository,
            IChangeLogRepository changeLogRepository,
            ServiceBillingContext serviceBillingContext,
            IConfiguration configuration,
                            GraphServiceClient graphServiceClient,
                            MicrosoftIdentityConsentAndConditionalAccessHandler consentHandler)
        {
            _graphServiceClient = graphServiceClient;
            _consentHandler = consentHandler;
            _billRepository = billRepository;
            _categoryRepository = categoryRepository;
            _clientAccountRepository = clientAccountRepository;
            _ministryRepository = ministryRepository;
            _logger = logger;
            _authorizationService = authorizationService;
            _businessAreaRepository = businessAreaRepository;
            _serviceBillingContext = serviceBillingContext;
            _fiscalPeriodRepository = fiscalPeriodRepository;
            _fiscalHistoryRepository = fiscalHistoryRepository;
            _changeLogRepository = changeLogRepository;
        }

        [Authorize]
        [Authorize(Roles = "GDXBillingService.FinancialOfficer, GDXBillingService.Owner, GDXBillingService.User")]
        public IActionResult Index(ChargeIndexSearchParamsModel searchModel)
        {
            IEnumerable<ServiceCategory> categories = _categoryRepository.GetAll();
            IEnumerable<BusinessArea> busareas = _businessAreaRepository.GetAll();
            IEnumerable<Ministry> ministries = _ministryRepository.GetAll();
            string previousQuarterString = _billRepository.GetPreviousQuarterString();
            string currentQuarterString = _billRepository.DetermineCurrentQuarter();
            ViewData["PreviousQuarterString"] = previousQuarterString;
            ViewData["CurrentQuarterString"] = currentQuarterString;
            IEnumerable<FiscalPeriod> fiscalPeriods = _fiscalPeriodRepository.GetAll().OrderByDescending(x => x.Period);
            List<string> fiscalPeriodsStrings = fiscalPeriods.Select(x => x.Period).ToList();
            fiscalPeriodsStrings.Remove(previousQuarterString);
            fiscalPeriodsStrings.Remove(currentQuarterString);
            ViewData["PreviousFiscals"] = fiscalPeriodsStrings.Distinct(); // not sure why there's duplicate entries in DEV...

            if (ministries != null && ministries.Any())
            {
                ViewData["Ministries"] = ministries;
            }
            if (categories != null && categories.Any())
            {
                if (!User.IsInRole("GDXBillingService.FinancialOfficer")
                    && User.IsInRole("GDXBillingService.Owner"))
                {
                    categories = categories.Where(c => GetUserOwnedServiceIds().Contains(c.ServiceId));
                }
                ViewBag.ServiceCategories = categories.ToList();
            }
           
            ViewBag.BusAreas = busareas.ToList();
            switch (searchModel?.QuarterFilter)
            {
                case "current":             
                    ViewData["FiscalPeriod"] = _billRepository.DetermineCurrentQuarter();
                    break;
                case "previous":
                    ViewData["FiscalPeriod"] = previousQuarterString;
                    break;
                case "next":
                    ViewData["FiscalPeriod"] = _billRepository.DetermineCurrentQuarter(_billRepository.DetermineStartOfNextQuarter());
                    break;
                case "all":
                    ViewData["FiscalPeriod"] = "all";
                    break;
                default:
                    ViewData["FiscalPeriod"] = searchModel?.QuarterFilter;

                    break;
            }
            ViewData["searchModel"] = searchModel;

            return View();
        }

        [HttpPost]
        public ActionResult GetBillsTable(ChargeIndexSearchParamsModel searchModel)
        {
            var isMinistryUser = User.IsInRole("GDXBillingService.User");
            string? ministryUserName = string.Empty;
            if (isMinistryUser) ministryUserName = User?.FindFirst("name")?.Value;
            if (searchModel != null && !string.IsNullOrEmpty(searchModel.QuarterFilter) &&
                searchModel.QuarterFilter.StartsWith("Fiscal"))
                searchModel.QuarterString = searchModel.QuarterFilter;

            IEnumerable<Bill> bills = QueryForCharges(searchModel, !String.IsNullOrEmpty(ministryUserName) ? ministryUserName : String.Empty);
            int count = bills.Any() ? bills.Count() : 0;
            
            if(searchModel != null && !String.IsNullOrEmpty(searchModel.QuarterFilter))
            {
                switch (searchModel.QuarterFilter)
                {
                    case "current":
                        ViewData["FiscalPeriod"] = _billRepository.DetermineCurrentQuarter();
                        break;
                    case "previous":
                        searchModel.QuarterString = _billRepository.GetPreviousQuarterString();
                        ViewData["FiscalPeriod"] = searchModel.QuarterString;
                        ViewData["IsPrevious"] = "yes";
                        FiscalPeriod? previousFiscal = _fiscalPeriodRepository.GetFiscalPeriodByString(searchModel.QuarterString);
                        if (previousFiscal == null)
                            throw new Exception($"Could not find fiscal period from database matching '{searchModel.QuarterString}'");
                        else
                            ViewData["PreviousFiscalId"] = previousFiscal.Id;
                        break;
                    case "next":
                        ViewData["FiscalPeriod"] = _billRepository.DetermineCurrentQuarter(_billRepository.DetermineStartOfNextQuarter());
                        break;
                    case "all":
                        ViewData["FiscalPeriod"] = "all";
                        count = 0;
                        foreach(Bill bill in bills)
                        {
                            count++;
                            if (bill.PreviousFiscalRecords.Any())
                                count += bill.PreviousFiscalRecords.Where(x => x.FiscalPeriod.Id != bill.CurrentFiscalPeriodId).Count();
                        }
                        break;
                    default:
                        searchModel.QuarterString = searchModel.QuarterFilter;
                        ViewData["FiscalPeriod"] = searchModel.QuarterString;
                        break;
                }
            }
            else
            {
                ViewData["FiscalPeriod"] = _billRepository.DetermineCurrentQuarter();
            }
            ViewData["ChargesReturnedByQuery"] = count;
          
            return PartialView("ChargesTable", bills);
        }

        public ActionResult Details(int id, int? historyId, bool isNew = false, bool isEdited = false)
        {
            Bill? bill = _billRepository.GetBill(id);
            try
            {
                if (bill == null)
                {
                    return NotFound();
                }
                ClientAccount? account = _clientAccountRepository.GetClientAccount(bill.ClientAccountId);
                ServiceCategory? serviceCategory = _categoryRepository.GetById(bill.ServiceCategoryId);
                ViewData["clientAccount"] = account != null ? account : "";
                ViewData["serviceCategory"] = serviceCategory != null ? serviceCategory : "";
                ViewData["isNew"] = isNew;
                ViewData["isEdited"] = isEdited;
                if(historyId > 0)
                {
                    FiscalHistory? fiscalHistory = bill.PreviousFiscalRecords?.FirstOrDefault(x => x.Id == historyId);
                    if (fiscalHistory == null)
                    {

Views/Shared/Unauthorized.cshtml
@{
    ViewData["Title"] = "Unauthorized";
}

<h1 class="text-danger">Unauthorized</h1>
<h2 class="text-danger">You seem to be missing authorization to view this resource. If you believe you are receiving this message in error
    please get in touch with us. This message is missing contact info at the moment. Maybe contact Alexander.Carmichael@gov.bc.ca, and I'll try to get you sorted.'
</h2>

Views/Shared/_Footer.cshtml
<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - Billing - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

Views/Shared/_Header.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    var user = User as ClaimsPrincipal;
    //  var isMinistryClient = user?.IsMinistryClient() ?? false;
    bool isAdmin = user != null && user.IsInRole("GDXBillingService.FinancialOfficer");
    bool isServiceOwner = user != null && user.IsInRole("GDXBillingService.Owner");
    bool isMinistryClient = user != null && user.IsInRole("GDXBillingService.User");
    <!--Should be one of "development" or "test" or empty string for banner div colour -->
    string? environmentName = @System.Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT"); 
}
@using Microsoft.AspNetCore.Authorization
@using System.Security.Claims
@inject IAuthorizationService AuthorizationService
<header class="@environmentName">
    <div class="banner">
        <a href="/">
            <img src="~/assets/BCID_H_rgb_rev.svg" alt="Go to the Government of British Columbia website" />
        </a>
        @if(!String.IsNullOrEmpty(environmentName))
        {
            <h1 class="site-title">GDX Service Billing: @environmentName</h1>
        }
        else
        {
            <h1 class="site-title">GDX Service Billing</h1>
        }
    </div>
    <div class="other">
        <!--
          This place is for anything that needs to be right aligned
          beside the logo.
        -->
    </div>
    <partial name="_LoginPartial" />
    <ul class="navbar-nav hamburger-menu">
        <li class="nav-item">
            <span class="navbar-text">
                <a class="nav-btn" id="nav-toggle">
                <i class="fas fa-bars" id="menu"></i>
            </a></span>
        </li>
    </ul>
</header>
<nav class="navigation-main" id="navbar">
    <div class="nav-container">
        <ul>
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            @if (!isMinistryClient)
            {
                <li id="create-account-link">@Html.ActionLink("Create Client Account", "Create", "ClientAccount")</li>
            }
            @if (isAdmin)
            {
                <li id="account-index-link">@Html.ActionLink("Manage Account", "Index", "ClientAccount")</li>
            }
            @if (isAdmin)
            {
                <li id="charge-index-link">@Html.ActionLink("View Quarterly Reports", "Index", "Bills")</li>
            }
            else if(isServiceOwner)
            {
                <li id="charge-index-link">@Html.ActionLink("View Reports for My Services", "Index", "Bills")</li>
            }

            @if (!isMinistryClient)
            {
                <li id="order-service-link">@Html.ActionLink("Order a Service", "AddServiceBilling", "Bills")</li>
            }
            @if (!isMinistryClient)
            {
                <li id="service-index-link">@Html.ActionLink("View Service Categories", "Index", "ServiceCategory")</li>
            }
            @if(isMinistryClient)
            {
                <li id="service-index-link">@Html.ActionLink("View My Team's Charges", "Index", "Bills")</li>
            }
            @if (isAdmin)
            {
                <li id="create-service-link">@Html.ActionLink("Create New Service", "Create", "ServiceCategory")</li>
            }
            @if (isAdmin)
            {
                <li id="organization-service-link">@Html.ActionLink("Manage Organizations", "Index", "Organization")</li>
            }
        </ul>
    </div>
</nav>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Billing</title>
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <script src="~/Scripts/webanalytics.js" type="text/javascript"></script>
</head>
<body>
    <partial name="_Header"/>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
        <!-- you can use this for a general puprose loading spinner -->
            <div id="loading-card">
            <div class="overlay"></div>
            <div class="spanner">
                <div class="loader"></div>
                <p>Loading...</p>
            </div>
            </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>  
    
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/redmond/jquery-ui.css"/>
    <script src="~/lib/font-awesome/all.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
   
    <div class="toast fade" id="info-toast">
        <div class="toast-header">
            <strong class="me-auto" id="toast-title-text">Placeholder Text</strong>
            <small id="toast-header-small-text">Placeholder small text</small>
            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
        <div id="toast-body">
            Placeholder toast body text
        </div>
        <div id="toast-links"></div>
    </div>
</body>
</html>

  <script>
        $('input,select').each(function () {
            var req = $(this).attr('data-val-required');
            if (undefined != req) {
                var label = $('label[for="' + $(this).attr('id') + '"]');
                var text = label.text();
                if (text.length > 0) {
                    label.append('<span style="color:red"> *</span>');
                }
            }
        });
  </script>