Models/ClientAccount.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using NuGet.Configuration;
using Service_Billing.Validation;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Service_Billing.Models
{
    // see https://apps.itsm.gov.bc.ca/confluence/display/GDXSB/Account+Setup for client documentation
    public class ClientAccount
    {
        [Key]
        public int Id { get; set; }

        /*	<sector/group> - <ministry acronym> - <sub group> - <full org/branch name> - <service>; e.g.: ECON – JTT – DataBC – WordPress; CITZ – OCIO – ISB. 
o	Note: not all naming convention components are required. The naming convention is used to easily group and sort Client Accounts along organizational lines.
*/
        [Required(ErrorMessage = "Add a client name")]
        [Display(Name = "Name")]
        public string? Name { get; set; }

        [BindRequired]
        //"must be unique, except for secondary accounts only used for alternative financial coding."

        [Display(Name = "CAS Client Number", Prompt = "Enter CAS Client Number")]
        public Int16? ClientNumber { get; set; } // three digit billing code

        //5-digits or combination of digits and letters
        [BindRequired]
        [RegularExpression(@"^.{5,5}$", ErrorMessage = "Please provide the five-digit responsibility centre code from the Corporate Accounting System.")]
        [Display(Name = "Responsibility Centre", Prompt = "Enter 5-digit Responsibility Centre code")]
        public string? ResponsibilityCentre { get; set; }

        [BindRequired]
        [RegularExpression(@"^.{5,5}$", ErrorMessage = "Please provide the five-digit service line code from the Corporate Accounting System.")]
        [Display(Name = "Service Line", Prompt = "Enter 5-digit Service Line code")]
        public int? ServiceLine { get; set; }

        [BindRequired]
        [Display (Prompt = "Enter 4-digit STOB code")]
        [RegularExpression(@"^.{4,4}$", ErrorMessage = "Please provide the ministry Standard Object of Expenditure (STOB) number.")]
        public Int16? STOB { get; set; }

        [Required(ErrorMessage = "A Project Code must be provided")]
        [RegularExpression(@"^.{7,7}$", ErrorMessage = "Please provide a ministry project code.")]
        [Display(Name = "Project", Prompt = "Enter 7-digit project code")]
        public string? Project { get; set; }

        [Display(Name = "Expense Authority", Prompt = "Start typing in your contact's last name")]
        [Required(ErrorMessage = "Please provide the name of the ministry expense authority")]
        public string? ExpenseAuthorityName { get; set; }

        [Display(Name = "Services Enabled")]
        public string? ServicesEnabled { get; set; } // string so we can have a list of id's, like "3, 6, 420"

        [Display(Name = "EA Approved")]
        public bool IsApprovedByEA { get; set; } = false;

        public bool IsActive { get; set; } = true;

        public string? Notes { get; set; }

        public virtual ICollection<Bill>? Bills { get; set; }

        public virtual ICollection<Contact>? Contacts { get; set; }

        [NotMapped]
        [Display(Name = "Primary Contact")]
        public virtual IEnumerable<Contact>? PrimaryContacts { get { return Contacts?.Where(x => x.ContactType == "primary"); } set { PrimaryContacts = value; } }

        [NotMapped]
        [Display(Name = "Financial Contacts")]
        public virtual IEnumerable<Contact>? FinancialContacts { get { return Contacts?.Where(x => x.ContactType == "financial"); } set { FinancialContacts = value; } }
        [NotMapped]
        [Display(Name = "Approver Contacts")]
        public virtual IEnumerable<Contact>? ApproverContacts { get { return Contacts?.Where(x => x.ContactType == "approver"); } set { ApproverContacts = value; } }
        /* This is the Primary Contact for the Client Account.  Normally there is only one.  
           This role can authorize billable service requests and changes to client account details including new services, 
           client account team membership, financial coding changes and SharePoint site access for their team.
        */
        [BindRequired]
        [Display(Name = "Primary Contact", Prompt = "Start typing in your contact's last name")]
        public string? PrimaryContact { get; set; }

     

        /* This role can authorize billable service requests and changes to client account details including new services, 
         * client account team membership, financial coding changes and SharePoint site access for their team.  */
        [Display (Prompt = "Start typing in your contact's last name")]
        [BindRequired]
        public string? Approver { get; set; }
       

        /* This role is not normally involved with service request approvals, though an exception can be made if the primary, 
         * or approvers are not available. The role can provide updated billing information.  
         * For quarterly billing, this role is a contact. */
        //  [Required(ErrorMessage = "Please include this contact")]
        [Display(Name = "Financial Contacts", Prompt = "Start typing in your contact's last name")]
        public string? FinancialContact { get; set; }
     
        [BindRequired]
        [NotMapped]
        public string AggregatedGLCode
        {
            get
            {
                return $"{ClientNumber}.{ResponsibilityCentre}.{ServiceLine}.{STOB}.{Project}";
            }
        }

        [Display( Name = "Organization")]
        [BindRequired]
        public int? OrganizationId { get; set; } = 0;//for ministry/organization tracking

    }
}
/* Client limits 
 * Primary Contacts (up to 2 allowed)
Approvers (multiples allowed)
Financial Contacts (multiples allowed)
Expense Authority (1 only)
*/
/* some validation concerns:
 * Client= 3 digits
Responsibility Centre= 5 digits
Service Line= 5 digits
STOB= 4 digits
Project= 7 digits
*/

ViewModels/ClientAccountViewModel.cs
using Service_Billing.Models;

namespace Service_Billing.ViewModels
{
    public class ClientAccountViewModel
    {
        public IEnumerable<ClientAccount> ClientAccounts { get; }

        //now that we don't have a separate table for client teams, this model is probably redundant. 
        public ClientAccountViewModel(IEnumerable<ClientAccount> clients)
        {
  
        }

    
    }
}

Controllers/ClientAccountController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Service_Billing.Models;
using Service_Billing.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Graph;
using Microsoft.Identity.Web;
using Service_Billing.Models.Repositories;
using Microsoft.Identity.Client;
using Service_Billing.Services.Email;
using Microsoft.AspNetCore.Authorization;
using Service_Billing.Filters;
using Service_Billing.Services.GraphApi;
using ClosedXML.Excel;
using System.Text.RegularExpressions;
using DocumentFormat.OpenXml.Office2019.Drawing.Model3D;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Razor.TagHelpers;
using DocumentFormat.OpenXml.InkML;

namespace Service_Billing.Controllers
{
    public class ClientAccountController : Controller
    {
        private readonly IClientAccountRepository _clientAccountRepository;
        private readonly IMinistryRepository _ministryRepository;
        private readonly IBillRepository _billRepository;
        private readonly IServiceCategoryRepository _categoryRepository;
        private readonly GraphServiceClient? _graphServiceClient;
        private readonly MicrosoftIdentityConsentAndConditionalAccessHandler _consentHandler;
        private readonly ILogger<ClientAccountController> _logger;
        private readonly string[]? _graphScopes;
        private readonly IEmailService _emailService;
        private readonly IGraphApiService _graphApiService;
        private readonly IAuthorizationService _authorizationService;
        private readonly IConfiguration _configuration;
        private readonly IBusinessAreaRepository _businessAreaRepository;
        private readonly IPeopleRepository _peopleRepository;
        private readonly IContactRepository _contactRepository;
        private readonly IConfidentialClientApplication cca;
        private readonly IChangeLogRepository _changeLogRepository;



        public ClientAccountController(ILogger<ClientAccountController> logger,
            IClientAccountRepository clientAccountRepository,
            IMinistryRepository ministryRepository,
            IBillRepository billRepository,
            IAuthorizationService authorizationService,
            IServiceCategoryRepository categoryRepository,
            IBusinessAreaRepository businessAreaRepository,
            IPeopleRepository peopleRepository,
            IChangeLogRepository changeLogRepository,
            IContactRepository contactRepository,

            IConfiguration configuration,
                            GraphServiceClient graphServiceClient,
                            MicrosoftIdentityConsentAndConditionalAccessHandler consentHandler,
                            IEmailService emailService,
                            IGraphApiService graphApiService)
        {
            _graphServiceClient = graphServiceClient;
            _consentHandler = consentHandler;

            _clientAccountRepository = clientAccountRepository;
            _ministryRepository = ministryRepository;
            _billRepository = billRepository;
            _categoryRepository = categoryRepository;
            _logger = logger;
            _graphScopes = configuration.GetValue<string>("DownstreamApi:Scopes")?.Split(' ');
            _emailService = emailService;
            _graphApiService = graphApiService;
            _authorizationService = authorizationService;
            _configuration = configuration;
            _businessAreaRepository = businessAreaRepository;
            _peopleRepository = peopleRepository;
            _contactRepository = contactRepository;
            cca = ConfidentialClientApplicationBuilder
                    .Create(_configuration.GetSection("AzureAd")["ClientId"])
                    .WithClientSecret(_configuration.GetSection("AzureAd")["ClientSecret"])
                    .WithAuthority(new Uri($"https://login.microsoftonline.com/{_configuration.GetSection("AzureAd")["TenantId"]}"))
                    .Build();
            _changeLogRepository = changeLogRepository;

        }

        // GET: ClientAccountController
        [Authorize]
        [Authorize(Roles = "GDXBillingService.FinancialOfficer, GDXBillingService.Owner, GDXBillingService.User")]
        public ActionResult Index(int ministryFilter, int numberFilter, string responsibilityFilter, string authorityFilter, string teamFilter, string keyword, string contactFilter)
        {
            // TODO: Add filtering options or Services Enabled and Notes
            // "Add “Notes” field (this section will allow admins to update to identify service ticket number or changes made to client account)"
            IEnumerable<Ministry> ministries = _ministryRepository.GetAll();
            ViewData["Ministries"] = ministries;
            ViewData["MinistryFilter"] = ministryFilter;
            ViewData["NumberFilter"] = numberFilter;
            ViewData["AuthorityFilter"] = authorityFilter;
            ViewData["ContactFilter"] = contactFilter;
            ViewData["ResponsibilityFilter"] = responsibilityFilter;
            ViewData["TeamFilter"] = teamFilter;
            ViewData["Keyword"] = keyword;

            var isMinistryUser = User.IsInRole("GDXBillingService.User");
            string? ministryUserName = string.Empty;
            if (isMinistryUser) ministryUserName = User?.FindFirst("name")?.Value;

            IEnumerable<ClientAccount> clients = GetFilteredAccounts(ministryFilter, numberFilter, responsibilityFilter, authorityFilter, teamFilter, keyword, contactFilter, ministryUserName ?? "");

            return View(clients);
        }


        // GET: ClientAccountController/Details/5
        [Authorize(Roles = "GDXBillingService.FinancialOfficer, GDXBillingService.Owner, GDXBillingService.User")]
        public ActionResult Details(int id, bool isNew = false, bool isEdited = false)
        {
            ClientAccount? account = _clientAccountRepository.GetClientAccount(id);
            if (account == null)
                return NotFound();
            ViewData["isNew"] = isNew;
            ViewData["isEdited"] = isEdited;
            // check if user ought to be able to view this record
            if (!User.IsInRole("GDXBillingService.FinancialOfficer"))
            {

                if (!String.IsNullOrEmpty(User.GetDisplayName()))
                {
                    if (!IsUserAccountContact(account))
                    {
                        if (!String.IsNullOrEmpty(account.ExpenseAuthorityName) && !account.ExpenseAuthorityName.ToLower().Contains(GetUserLastName().ToLower()))
                        {
                            return View("Unauthorized");
                        }
                    }
                }
                else
                {
                    _logger.LogWarning($"User tried to view Account details for client account with id: {id}, but user's name could not be discerned");
                    return View("Unauthorized");
                }
            }
            ViewData["ChangeLogs"] = _changeLogRepository.GetByEnityIdAndType(account.Id, "clientAccount");

            return View(account);
        }

        // GET: ClientAccountController/Edit/5
        public ActionResult Edit(int id)
        {
            ClientAccount? account = _clientAccountRepository.GetClientAccount(id);

            if (account == null)
                return NotFound();

            return View(account);
        }

        // POST: ClientAccountController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ClientAccount model, int[] contactIds, int[] personIds, string[] displayNames, string[] contactTypes)
        {
            try
            { // validation for contacts as foreign entities gave me a lot of trouble and ultimately I found this the most reasonable solution.
                ModelState.Clear();
                bool hasApprover = false;
                bool hasFinancial = false;
                bool hasPrimary = false;

                for(int i = 0; i < contactIds.Length; i++)
                {
                        switch(contactTypes[i])
                        {
                        case "approver":
                            if (!String.IsNullOrEmpty(displayNames[i]))
                                hasApprover = true;
                            break;
                        case "financial":
                            if (!String.IsNullOrEmpty(displayNames[i]))
                                hasFinancial = true;
                            break;
                        case "primary":
                            if (!String.IsNullOrEmpty(displayNames[i]))
                                hasPrimary = true;
                            break;

                    }
                }

                if (!hasPrimary)
                    ModelState.AddModelError("PrimaryContact", "Please include a primary contact");
                if (!hasApprover)
                    ModelState.AddModelError("Approver", "Please include at least one approver contact");
                if (!hasFinancial)
                    ModelState.AddModelError("FinancialContact", "Please include at least one financial contact");
                
                if (!ModelState.IsValid)
                {
                    ClientAccount? account = _clientAccountRepository.GetClientAccount(model.Id);
                    IEnumerable<Models.Contact>? remainingContacts = account?.Contacts?.Where(x => contactIds.Contains(x.Id));
                    model.Contacts = remainingContacts?.ToList(); //don't include contacts that were removed.
                    return View(model);
                }

                await ResolveContactUpdates(model.Id, contactIds, personIds, displayNames, contactTypes);
                string user = User.Claims.FirstOrDefault(c => c.Type == "name")?.Value ?? "NAME NOT DETERMINED";

Views/ClientAccount/Approve.cshtml
<h2>Approve this account?</h2>

<p>
    Are you sure you want to approve this account?
</p>

<form asp-action="Approve" method="post">
    @Html.AntiForgeryToken()
    <button type="submit" class="btn btn-primary">Approve</button>
</form>

Views/ClientAccount/ContactSection.cshtml
@model Person
@{

}

Views/ClientAccount/Edit.cshtml
@model Service_Billing.Models.ClientAccount

@{
    ViewData["Title"] = $"{Model.Id}: Edit Client Account";
    Layout = "_Layout";
}
@{
    int i = 0; // for contact indices
}

<h1>Edit</h1>

<h4>ClientAccount</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" id="editForm">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="@Model.Name" class="control-label"></label>
                <input asp-for="@Model.Name" class="form-control" value="@Model.Name"/>
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.ClientNumber" class="control-label"></label>
                <input asp-for="@Model.ClientNumber" class="form-control" value="@Model.ClientNumber" data-val="true" data-val-required="A CAS Client Number must be provided"/>
                <span asp-validation-for="@Model.ClientNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.ResponsibilityCentre" class="control-label"></label>
                <input asp-for="@Model.ResponsibilityCentre" class="form-control" value="@Model.ResponsibilityCentre" data-val="true" data-val-required="Please Provide a five character RC code"/>
                <span asp-validation-for="@Model.ResponsibilityCentre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.ServiceLine" class="control-label"></label>
                <input asp-for="@Model.ServiceLine" class="form-control" value="@String.Format("{0:00000}", Model.ServiceLine)" maxlength="5" data-val="true" data-val-required="Please Provide a five character Service Line code" />
                <span asp-validation-for="@Model.ServiceLine" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.STOB" class="control-label"></label>
                <input asp-for="@Model.STOB" class="form-control" value="@String.Format("{0:0000}", Model.STOB)" maxlength="4" data-val-required="Please Provide a four character SToB number" />
                <span asp-validation-for="@Model.STOB" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Project" class="control-label"></label>
                <input asp-for="@Model.Project" class="form-control" value="@Model.Project" />
                <span asp-validation-for="@Model.Project" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.ExpenseAuthorityName" class="control-label"></label>
                <input asp-for="@Model.ExpenseAuthorityName" class="form-control contact-input" value="@Model.ExpenseAuthorityName" id="ea-input" />

                <span asp-validation-for="@Model.ExpenseAuthorityName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Notes" class="control-label"></label>
                <textarea asp-for="@Model.Notes" class="form-control" value="@Model.Notes" > </textArea>
                <span asp-validation-for="@Model.Notes" class="text-danger"></span>
            </div>

            <label asp-for="@Model.Contacts" class="control-label">Primary Contacts</label>
            <div id="primary-contacts">
                   
            <!-- Handling contacts as one collection with different types was a real pain. Not sure I would do it again. -->
            @foreach(Contact? contact in Model.Contacts)
            {
              if(contact.ContactType == "primary")
              {  
                <div class="form-group">
                  <input asp-for="@contact.Person.DisplayName" name="displayNames" id="contact.Person.DisplayName" class="form-control contact-input" class="contactInput" placeholder="start entering surname to search" 
                    data-val="true"
                    data-val-required="Please provide a primary contact"/>
                  <input asp-for="@contact.ContactType" name="contactTypes" class="contact-type" type="hidden" value="primary"/>
                  <input asp-for="@contact.PersonId" name="personIds" class="id-input" type="hidden" />
                  <input asp-for="@contact.Id" name="contactIds" type="hidden" class="contact-id" />
                  @if(contact != Model.PrimaryContacts.First())
                  {     
                    <a id="remove-contact" onclick="removeContactInput(event)">remove</a>
                  }
                </div>
              }
            }  
                
              <a id="add-primary" onclick="addContact('primary')">Add a second Primary Contact?</a>
              <div>
                <span asp-validation-for="@Model.PrimaryContact" class="text-danger"></span>
              </div>
            </div>

            <label asp-for="@Model.Contacts" class="control-label">Approvers</label>
                
            <div id="approver-contacts">
            @foreach(Contact contact in Model.Contacts)
            {
                if (contact.ContactType == "approver")
                {
                    <div class="form-group">
                        <input class="form-control contact-input" asp-for="@contact.Person.DisplayName" name="displayNames" id="contact_@i" placeholder="start entering surname to search"
                          data-val="true"
                      data-val-required="Please include at least one approver contact"/>
                    <input asp-for="@contact.ContactType" name="contactTypes" class="contact-type" type="hidden" value="approver"/>
                    <input asp-for="@contact.PersonId" name="personIds" class="id-input" type="hidden" />
                    <input asp-for="@contact.Id" name="contactIds" class="contact-id" type="hidden" />
                    @if (contact != Model.ApproverContacts?.First())
                    {
                      <a id="remove-contact" onclick="removeContactInput(event)">remove</a>
                    }
                    </div> 
                }
              i++;
            }
              <a id="add-approver" onclick="addContact('approver')">Add an approver contact?</a>
              <div>
                <span asp-validation-for="@Model.Approver" class="text-danger"></span>
              </div>
            </div>

            <label asp-for="@Model.Contacts" class="control-label contact-input">Financial Contacts</label>
            <div id="financial-contacts">

            @foreach(Contact contact in Model.Contacts)
            {
              if(contact.ContactType == "financial")
              {
                  <div class="form-group">
                  <input class="form-control contact-input" asp-for="@contact.Person.DisplayName" name="displayNames" placeholder="start entering surname to search" 
                    data-val="true"
                      data-val-required="Please include at least one financial contact"/>
                  <input asp-for="@contact.ContactType" name="contactTypes" class="contact-type" type="hidden" value="financial"/>
                  <input asp-for="@contact.PersonId" name="personIds" class="id-input" type="hidden" />
                  <input asp-for="@contact.Id" name="contactIds" type="hidden" class="contact-id" />
                  @if(contact != Model.FinancialContacts?.First())
                  {
                    <a id="remove-contact" onclick="removeContactInput(event)">remove</a>
                  }
                </div>
              }
            }

              <a id="add-financial" onclick="addContact('financial')">Add a financial contact?</a>
              <div>
                <span asp-validation-for="@Model.FinancialContact" class="text-danger"></span>
              </div>
            </div>
              
            <label asp-for="@Model.IsApprovedByEA">EA Approved?</label>

            <input type="checkbox" asp-for="@Model.IsApprovedByEA" checked="@Model.IsApprovedByEA" />
            <span asp-validation-for="@Model.IsApprovedByEA" class="text-danger"></span>
               
            <div class="form-group">
                <label asp-for="@Model.ServicesEnabled" class="control-label"></label>
                <input asp-for="@Model.ServicesEnabled" class="form-control" value="@Model.ServicesEnabled" />
                <span asp-validation-for="@Model.ServicesEnabled" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="@Model.Id" class="form-control" id="id"/>
            <input type="hidden" asp-for="@Model.OrganizationId" class="form-control" />        
            <br />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>   
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        var i = 0;
        const contactListUrl = window.location.origin + "/ClientAccount/SearchForContact";
        $(document).ready(function () {
            makeContactInputs();
          if(@Model.PrimaryContacts?.Count() > 1){
              $("#add-primary").hide();
          }
        });

        var DidContactActuallyChange = ((id, displayName, type, event) => {
            var url = `@Url.Action("DidContactChange", "ClientAccount")` + `?accountId=${id}` + `&name=${displayName}` + `&type=${type}`;
          var xhr = new XMLHttpRequest();
            var inputGroup = $(event.target);
          xhr.onreadystatechange = function () {
              if (this.readyState == 4 && this.status == 200) {
                  if(xhr.responseText === 'true'){
                      inputGroup.siblings('.id-input').val(0);
                      inputGroup.siblings('.contact-id').val(0);
                      if(inputGroup.val() ===''){
                          removeContactInput(event);
                      }
                  }
              }
          };

          xhr.open('get', url);
          xhr.send();
        });

       const makeContactInputs = (() => {
          $(".contact-input").each(function () {
              $(this).autocomplete({
                source: contactListUrl,
                delay: 100
              });
            });
             $( ".contact-input" ).on( "autocompleteselect", function( event, ui ) {
            updateContactPerson(ui.item.label, event);
        } );
         $( ".contact-input" ).on( "change", function( event, ui ) {
           if(!ui){   
             var inputGroup = $(event.target);
               var accountId = $('#id').val();
               DidContactActuallyChange(accountId, inputGroup.val(), inputGroup.siblings('.contact-type').val(), event)
           }
        } );
        });

       const updateContactPerson = ((displayName, e) => {
         var inputGroup = $(e.target);
        
          var url = `@Url.Action("GetAccountContact", "ClientAccount")` + `?displayName=${displayName}`;
          var xhr = new XMLHttpRequest();

          xhr.onreadystatechange = function () {
              if (this.readyState == 4 && this.status == 200) {
                  var data = JSON.parse(xhr.response);
                  var id = data.id;
                  var mail = data.mail;
                  // Use string selectors for siblings
                  inputGroup.siblings('.id-input').val(id);
              }
          };

          xhr.open('get', url);
          xhr.send();
      });

      const addContact = ((contactType) => {

          var html = `<div class="form-group">
                       <input asp-for="contact_Person_DisplayName" name="displayNames" class="form-control contact-input" class="contactInput" placeholder="start entering surname to search" />
                       <input asp-for="contact_Person_ContactType" name="contactTypes" type="hidden" value="${contactType}"/>
                       <input asp-for="contact_Person_PersonId" name="personIds" class="id-input" type="hidden"/>
                       <input asp-for="contact_Id" name="contactIds" class="contact-id-input" type="hidden" value="0"  />
                        <a id="remove-contact" onclick="removeContactInput(event)">remove</a>
                     </div>`;
           $(`#${contactType}-contacts`).append(html);
           if(contactType === 'primary'){
            $("#add-primary").hide();
           }
           else if(contactType === 'financial'){
            $("#add-financial").hide();
           }
          makeContactInputs();
      }); 

      const removeContactInput = ((e, contactType) => {
        e.target.parentElement.remove();
          if(contactType === 'primary'){
            $("#add-primary").show();
          }
          else if (contactType === 'financial'){
             $("#add-financial").show();
          }
      });
    </script>
}