ServiceBilling.API/ServiceBilling.BillingManagement.UI/Models/ServiceCategory.cs
using System.ComponentModel.DataAnnotations;

namespace ServiceBilling.BillingManagement.UI.Models
{
    public class ServiceCategory
    {
        public Guid ServiceCategoryId { get; set; }
        
        [StringLength(100)]
        [Required(ErrorMessage = "Please enter a name")]
        public string Name { get; set; } = string.Empty;

        [StringLength(100)]
        [Display(Name = "GDX Business Area")]
        [Required(ErrorMessage = "Please enter a business area")]
        public string GdxBusinessArea { get; set; } = string.Empty;
        public string Costs { get; set; } = string.Empty;

        [StringLength(1000, ErrorMessage = "Description should not be longer than 1000 characters")]
        public string Description { get; set; } = string.Empty;
        
        public string UOM { get; set; } = string.Empty;

        public bool IsActive { get; set; } = false;
    }
}

ServiceBilling.API/ServiceBilling.BillingManagement.UI/Controllers/ServiceCategoryController.cs
using Microsoft.EntityFrameworkCore;
﻿using CsvHelper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using ServiceBilling.BillingManagement.UI.Models;
using ServiceBilling.BillingManagement.UI.Models.Repositories;
using ServiceBilling.BillingManagement.UI.ViewModels;

namespace ServiceBilling.BillingManagement.UI.Controllers
{
    public class ServiceCategoryController : Controller
    {
        private readonly IServiceCategoryRepository _serviceCategoryRepository;

        public ServiceCategoryController(IServiceCategoryRepository serviceCategoryRepository)
        {
            _serviceCategoryRepository = serviceCategoryRepository;
        }

        public async Task<IActionResult> Index()
        {
            ServiceCategoryListViewModel model = new ServiceCategoryListViewModel
            {
                ServiceCategories = (await _serviceCategoryRepository.GetAllServiceCategoriesAsync()).ToList()
            };

            return View(model);
        }

        //public async Task<IActionResult> Details()
        //{
        //}

        public async Task<IActionResult> Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add([Bind("Name,GdxBusinessArea,Costs,Description,UOM")] ServiceCategory serviceCategory)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    await _serviceCategoryRepository.AddServiceCategoryAsync(serviceCategory);
                    return RedirectToAction(nameof(Index));
                }

            }
            catch (Exception ex) 
            {
                ModelState.AddModelError("", $"Adding the service category, please try again! Error: {ex.Message}");    
            }

            return View();
        }

        [HttpGet]
        public IActionResult Edit(Guid id)
        {
            ServiceCategory? serviceCategory = _serviceCategoryRepository.GetById(id);
            if (serviceCategory == null)
            {
                return NotFound();
            }

            return View(serviceCategory);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ServiceCategory serviceCategory)
        {
            try
            {
                _serviceCategoryRepository.Update(serviceCategory);
            }
            catch (DbUpdateException ex)
            {

            }
            ServiceCategoryListViewModel model = new ServiceCategoryListViewModel
            {
                ServiceCategories = (await _serviceCategoryRepository.GetAllServiceCategoriesAsync()).ToList()
            };
            return View("index", model);
        }

        public async Task<FileResult> Export()
        {
            var serviceCategories = (await _serviceCategoryRepository.GetAllServiceCategoriesAsync()).ToList();

            var fileData = ExportServiceCategoriesToCsv(serviceCategories);

            return File(fileData, "text/csv", $"{Guid.NewGuid()}.csv");
        }

        public byte[] ExportServiceCategoriesToCsv(List<ServiceCategory> serviceCategories)
        {
            using var memoryStream = new MemoryStream();
            using (var streamWriter = new StreamWriter(memoryStream))
            {
                using var csvWriter = new CsvWriter(streamWriter);
                csvWriter.WriteRecords(serviceCategories);
            }

            return memoryStream.ToArray();
        }
    }
}

ServiceBilling.API/ServiceBilling.BillingManagement.UI/Views/ServiceCategory/Add.cshtml
@model ServiceCategory

<h2>Create New Service Category</h2>
<hr />

<form method="post" asp-controller="ServiceCategory" asp-action="Add">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="mb-3">
        <label asp-for="Name" class="form-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="GdxBusinessArea" class="form-label"></label>
        <input asp-for="GdxBusinessArea" class="form-control" />
        <span asp-validation-for="GdxBusinessArea" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Costs" class="form-label"></label>
        <input asp-for="Costs" class="form-control" />
        <span asp-validation-for="Costs" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="UOM" class="form-label"></label>
        <input asp-for="UOM" class="form-control" />
        <span asp-validation-for="UOM" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Description" class="form-label"></label>
        <textarea asp-for="Description" class="form-control" rows="5" cols="50" style="resize: none;"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="IsActive" class="form-label"></label>
        <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
        <span asp-validation-for="IsActive" class="text-danger"></span>
    </div>

    <input type="submit" value="Add category" class="btn btn-primary" />
</form>
<div>
    <a asp-controller="ServiceCategory" asp-action="Index">Back to overview</a>
</div>

ServiceBilling.API/ServiceBilling.BillingManagement.UI/Views/ServiceCategory/Edit.cshtml
@model ServiceCategory

<h1>Edit</h1>

<h4>ServiceCategory</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ServiceCategoryId" />
            <div class="form-group">
                <label asp-for="GdxBusinessArea" class="control-label"></label>
                <input asp-for="GdxBusinessArea" class="form-control" readonly="true" />
                <span asp-validation-for="GdxBusinessArea" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Costs" class="control-label"></label>
                <input asp-for="Costs" class="form-control" />
                <span asp-validation-for="Costs" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="UOM" class="control-label"></label>
                <input asp-for="UOM" class="form-control" />
                <span asp-validation-for="UOM" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ServiceBilling.API/ServiceBilling.BillingManagement.UI/Views/ServiceCategory/Index.cshtml
@model ServiceCategoryListViewModel

<h2>Service Category List</h2>
<a asp-controller="ServiceCategory" asp-action="Add" class="btn btn-primary">Add New</a>
@if(!Model.ServiceCategories.Any())
{
    <p>No results</p>
}

<table class="table">
    <tr>
        <th>Name</th>
        <th>Business Area</th>
        <th>Costs</th>
        <th>Description</th>
        <th>Unit of Measure</th>
        <th>Is Active?</th>
    </tr>
    @foreach (var category in Model.ServiceCategories)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => category.GdxBusinessArea)
            </td>
            <td>
                @Html.DisplayFor(modelItem => category.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => category.Costs)
            </td>
            <td>
                @Html.DisplayFor(modelItem => category.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => category.UOM)
            </td>
            <td>
                @Html.DisplayFor(modelItem => category.IsActive)
            </td>
            
            <td>
                <a asp-action="Edit" asp-route-id="@category.ServiceCategoryId">Edit</a> |
                <a asp-action="Delete" asp-route-id="@category.ServiceCategoryId">Delete</a>
            </td>
        </tr>
    }
</table>

<div>
    <a asp-controller="ServiceCategory" asp-action="Export" class="btn btn-primary">Export Service Categories</a>
</div>